### ISSUE TITLE
From which revision of Opal is this built?

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/opal-node-runtime#1]
Please add this information to the readme or commits (like in `opal-node-runtime`).

**Comment by ggrossetie** [comment]
I've added this information in the release page: https://github.com/Mogztter/asciidoctor-opal-node-runtime/releases

This project is built using a fork of Opal: https://github.com/Mogztter/opal/tree/asciidoctor
In this fork, I've commented out unused modules from `opal/opal.rb`.

**Comment by jirutka** [comment]
👍 Thanks!
