### ISSUE TITLE
Rename module to @asciidoctor/opal-runtime

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/opal-node-runtime#113]
Given that this module is crucial to Asciidoctor.js, and bears the name Asciidoctor, I propose graduating it to the Asciidoctor organization and publishing it under the @asciidoctor namespace on npm. The most logical choice for the module name is @asciidoctor/opal-runtime.

**Comment by ggrossetie** [comment]
@mojavelinux I think we should move this repository under the @asciidoctor org as well (on GitHub).

**Comment by mojavelinux** [comment]
Let's do it. I've given you transfer permissions.
